---
scenario:
  name: fedora
platforms:
  - name: fedora-30
    image: dokken/fedora-30
    command: /usr/lib/systemd/systemd
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: fedora-31
    image: dokken/fedora-31
    command: /usr/lib/systemd/systemd
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  inventory:
    host_vars:
      fedora-30:
        inspec_version: el7
        ansible_python_interpreter: /usr/bin/python3
      fedora-31:
        inspec_version: el7
        ansible_python_interpreter: /usr/bin/python3
