---
- name: Ensure Sensu Go component is installed
  package:
    name: "sensu-go-{{ component }}"
    state: present
  register: sensu_go_install_component
  retries: 6
  delay: 10
  until: sensu_go_install_component is not failed
