---
- name: restart sensu-backend
  service:
    name: sensu-backend
    state: restarted
  notify: wait for sensu-backend to accept connections
  when: sensu_go_final_services.backend.state != 'stopped'

- name: wait for sensu-backend to accept connections
  wait_for:
    port: 8081
    connect_timeout: 1

- name: restart sensu-agent
  service:
    name: sensu-agent
    state: restarted
  when: sensu_go_final_services.agent.state != 'stopped'

- name: update apt cache
  apt:
    update_cache: true

- name: yum-clean-metadata
  command: yum clean metadata
  args:
    warn: no
