---
- name: restart sensu-backend
  service:
    name: sensu-backend
    state: restarted
  notify: wait for sensu-backend to accept connections

- name: wait for sensu-backend to accept connections
  wait_for:
    port: 8081
    connect_timeout: 1

- name: restart sensu-agent
  service:
    name: sensu-agent
    state: restarted

- name: update apt cache
  apt:
    update_cache: true
