---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: yaml,timer,profile_tasks
      stdout_callback: yaml
      fact_caching: jsonfile
      fact_caching_connection: ./cache
      poll_interval: 3
      forks: 100
    connection:
      pipelining: true
  playbooks:
    prepare: ../shared/prepare.yml
    create: ../shared/create.yml
    destroy: ../shared/destroy.yml
    converge: ../shared/playbook.yml
    verify: ../shared/verify.yml
  lint:
    name: ansible-lint
verifier:
  name: inspec
  directory: ../shared/tests/
  lint:
    name: rubocop
