---
- name: Verify
  hosts: all
  become: true
  vars:
    inspec_download_source_dir: /usr/local/src
    inspec_bin: /opt/inspec/bin/inspec
    inspec_test_directory: "/tmp/molecule/inspec"
    inspec_downloads:
      el6:
        url: https://packages.chef.io/files/stable/inspec/4.18.100/el/6/inspec-4.18.100-1.el6.x86_64.rpm
        sha256: 7f4b624a101a10d71c172c1e642e4206797d132eb23df542a847f532da4fcdc9
      el7:
        url: https://packages.chef.io/files/stable/inspec/4.18.100/el/7/inspec-4.18.100-1.el7.x86_64.rpm
        sha256: bf04ce6ee98ccc7ceecb8462faed04a32e714af24b32447696f35b6d2742ee78
      ubuntu1604:
        url: https://packages.chef.io/files/stable/inspec/4.18.100/ubuntu/16.04/inspec_4.18.100-1_amd64.deb
        sha256: abb357be3be75667db0aea9b1f72e974fdaba1c6df41530787a60b9282d906a8
      ubuntu1804:
        url: https://packages.chef.io/files/stable/inspec/4.18.100/ubuntu/18.04/inspec_4.18.100-1_amd64.deb
        sha256: abb357be3be75667db0aea9b1f72e974fdaba1c6df41530787a60b9282d906a8
    inspec_package_deps:
      - lsof
      - net-tools
  tasks:
    - import_tasks: inspec.yml
    - name: Execute all custom module test plays
      include_tasks: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/modules/*.yml"
