---
- name: Verify
  hosts: all
  become: true
  vars:
    inspec_download_source_dir: /usr/local/src
    inspec_bin: /opt/inspec/bin/inspec
    inspec_test_directory: "/tmp/molecule/inspec"
    inspec_downloads:
      el6:
        url: https://packages.chef.io/files/stable/inspec/4.3.2/el/6/inspec-4.3.2-1.el6.x86_64.rpm
        sha256: 7f7a4df4c0d956f38b541552c8ab2e832b2437b69b0337a67bb24fcbb807bcbe
      el7:
        url: https://packages.chef.io/files/stable/inspec/4.3.2/el/7/inspec-4.3.2-1.el7.x86_64.rpm
        sha256: 37151ff63cdbc8522f5ecd6a7d9c8bf7ca8fc68b9aad7000a40c1c9d8ba5c9b2
      ubuntu1404:
        url: https://packages.chef.io/files/stable/inspec/4.3.2/ubuntu/14.04/inspec_4.3.2-1_amd64.deb
        sha256: 343ec7b04e55aa9cb654c2925c9d40f98980d0ea376552c81582e86c7073ea8a
      ubuntu1604:
        url: https://packages.chef.io/files/stable/inspec/4.3.2/ubuntu/16.04/inspec_4.3.2-1_amd64.deb
        sha256: 343ec7b04e55aa9cb654c2925c9d40f98980d0ea376552c81582e86c7073ea8a
      ubuntu1804:
        url: https://packages.chef.io/files/stable/inspec/4.3.2/ubuntu/18.04/inspec_4.3.2-1_amd64.deb
        sha256: 343ec7b04e55aa9cb654c2925c9d40f98980d0ea376552c81582e86c7073ea8a
    inspec_package_deps:
      - lsof
      - net-tools
  tasks:
    - import_tasks: inspec.yml
    - name: Execute all custom module test plays
      include_tasks: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/modules/*.yml"
