---
scenario:
  name: amazonlinux
platforms:
  - name: amazonlinux-1
    image: dokken/amazonlinux
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
  - name: amazonlinux-2
    image: dokken/amazonlinux-2
    command: /usr/lib/systemd/systemd
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  inventory:
    host_vars:
      amazonlinux-1:
        sensu_go_repos_overrides:
          yum:
            rpm: https://packagecloud.io/sensu/stable/el/6/x86_64
            rpm-src: https://packagecloud.io/sensu/stable/el/6/SRPMS
        sensu_go_community_repos_overrides:
          yum:
            rpm: https://packagecloud.io/sensu/community/el/6/x86_64
            rpm-src: https://packagecloud.io/sensu/community/el/6/SRPMS
        inspec_version: el6
      amazonlinux-2:
        sensu_go_repos_overrides:
          yum:
            rpm: https://packagecloud.io/sensu/stable/el/7/x86_64
            rpm-src: https://packagecloud.io/sensu/stable/el/7/SRPMS
        sensu_go_community_repos_overrides:
          yum:
            rpm: https://packagecloud.io/sensu/community/el/7/x86_64
            rpm-src: https://packagecloud.io/sensu/community/el/7/SRPMS
        inspec_version: el7
