---
scenario:
  name: debian
platforms:
  - name: debian-8
    image: dokken/debian-8
    command: /lib/systemd/systemd
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: debian-9
    image: dokken/debian-9
    command: /lib/systemd/systemd
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: debian-10
    image: dokken/debian-10
    command: /lib/systemd/systemd
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  inventory:
    host_vars:
      debian-8:
        inspec_version: ubuntu1604
        sensu_go_manage_community_repo: false
      debian-9:
        inspec_version: ubuntu1604
        sensu_go_manage_community_repo: false
      debian-10:
        inspec_version: ubuntu1804
        sensu_go_manage_community_repo: false
